# Generated by Django 6.0.2 on 2026-02-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEconomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesse', models.CharField(choices=[('1', 'Nada'), ('2', 'Pouco'), ('3', 'Um pouco'), ('4', 'Interessado'), ('5', 'Muito interessado')], default='3', max_length=1, verbose_name='O quão interessado está?')),
                ('quantidade_marmitas', models.IntegerField(verbose_name='Quantas marmitas por semana?')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Como é seu nome?')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Informe seu WhatsApp')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
