# Generated by Django 6.0.2 on 2026-02-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadeconomia',
            name='marmitas_consumidas',
            field=models.IntegerField(default=0),
        ),
    ]
